### ISSUE TITLE
Improve the Read Me

### ISSUE THREAD

**Issue by kocsismate** [woohoolabs/harmony#13]
If you are a native or fluent English-speaker, please proofread the Read Me file.

**Comment by yarwest** [comment]
@kocsismate Hello, I'd love to proofread and edit your README for you :) I use English on a daily basis and I have achieved my Cambridge Advanced English certificate.

**Comment by kocsismate** [comment]
Cool, that would be nice rom you! I'll accept the already submitted PRs after I've finished working, so I would advice you to wait until they got merged in order to avoid conflicts.

**Comment by yarwest** [comment]
Sure thing! I'll probably take a look at the entire thing later today or tomorrow :)
