### ISSUE TITLE
new install error

### ISSUE THREAD

**Issue by persianphilosopher** [woohoolabs/harmony#22]
I have been using this package for a few months now but as of two days ago, this is what I get when I try to install it via composer:

    - Installation request for woohoolabs/harmony ^5.0 -> satisfiable by woohoolabs/harmony[5.0.0].
    - woohoolabs/harmony 5.0.0 requires psr/http-message-implementation ^1.0.0 -> no matching package found.

Any suggestions?

**Comment by persianphilosopher** [comment]
I found the solution via your yin package:
https://github.com/woohoolabs/yin/issues/32

**Comment by kocsismate** [comment]
Cool that you found out the problem :) I also wrote about it in the install section of Harmony's read me, I hope that the text is clear enough. if not, I'll try to rephrase it.
