### ISSUE TITLE
LaminasEmitterMiddleware not available in the middleware

### ISSUE THREAD

**Issue by dewelopinweb** [woohoolabs/harmony#29]
LaminasEmitterMiddleware not available in the middleware.
Please, replace in example "Finally, launch the app:":
1. `use WoohooLabs\Harmony\Middleware\LaminasEmitterMiddleware;` => `use WoohooLabs\Harmony\Middleware\HttpHandlerRunnerMiddleware;`

2. `->addMiddleware(new LaminasEmitterMiddleware(new SapiEmitter()))` => `->addMiddleware(new HttpHandlerRunnerMiddleware(new SapiEmitter()))`

**Comment by kocsismate** [comment]
I believe you are using an older version of Harmony, aren't you? https://github.com/woohoolabs/harmony/releases/tag/7.1.0 added the `LaminasEmitterMiddleware`, as well as deprecated `HttpHandlerRunnerMiddleware`.
