### ISSUE TITLE
Return a Response object for all the middlewares.

### ISSUE THREAD

**Issue by superbull** [woohoolabs/harmony#5]
I really like the simplicity of this framework. 

Recently I play around with some third party middlewares like the CORS middleware from [oscarotero/psr7-middlewares](https://github.com/oscarotero/psr7-middlewares). It does not work with the harmony framework.

I found it is because harmony do not care whether middlewares `return` the **Response** object. But nearly all the other middlewares follow this rule:

> It can do whatever is appropriate with these objects. The only hard requirement is that a middleware **MUST** `return` an instance of `\Psr\Http\Message\ResponseInterface`. Each middleware **SHOULD** invoke the next middleware and pass it Request and Response objects as arguments.

which is quoted from the documentation of slimframework: http://www.slimframework.com/docs/concepts/middleware.html

Is this mechanism by design?

I think it would be nice that harmony framework can work with most of the third party middlewares out there.

**Comment by kocsismate** [comment]
That would be awesome indeed if Harmony could work well with third party middlewares! So thank you really much for the report as the current mechanism wasn't intentional. :)

Could you tell me other details about your setup? Did you use any official Harmony middleware along with the CORS one? If so, I do hope the only problem is that Harmony's middlewares don't return a response (as you said in the title of the issue).

**Comment by kocsismate** [comment]
I just pushed the fixes to the master branch! Could you ensure if it works for you?

**Comment by superbull** [comment]
hi @kocsismate , after this modification, everything works. Below is my setup:

``` php
$app
    ->addMiddleware('cors', $corsMiddleware)
    ->addMiddleware("fast_route", new FastRouteMiddleware($router))
    ->addMiddleware("dispatcher", new DispatcherMiddleware($container))
    ->addFinalMiddleware("responder", new DiactorosResponderMiddleware(new SapiEmitter()));
```

Actually I am also working with your `yin-middlewares`, I think there are also some modifications needed. For example, in `JsonApiDispatcherMiddleware.php` an `ErrorDocument` is returned directly from the middleware:

``` php
// JsonApiDispatcherMiddleware.php

...
if ($callable === null) {
    return $this->getDispatchErrorDocument($this->getDispatchError())->getResponse($response);
}
...
```

**Comment by kocsismate** [comment]
Good job with the PR, I'll release Harmony 2.3 shortly with this fix! Your comment on Yin-middlewares is also valid, I'll address it soon.

**Comment by kocsismate** [comment]
I've done with the release: Harmony will trigger a deprecated notice if a middleware returns with a Response.

**Comment by superbull** [comment]
good news!
