### ISSUE TITLE
What's the point of the "terminated" property?

### ISSUE THREAD

**Issue by superbull** [woohoolabs/harmony#7]
In the current code, it seems the `terminated` property of the class `Harmony` is useless.

Is there any use case for this?

**Comment by kocsismate** [comment]
Yes, you are right, there is no need for it anymore, so I've just removed it in my last commit (https://github.com/woohoolabs/harmony/commit/442edf4d0521d1970e47667a73bf9c955375186e)! Originally, It helped to ensure that final middlewares are only run once (but I became unsure if it was really needed).
