### ISSUE TITLE
Use StyleCI for CS checks AND fix

### ISSUE THREAD

**Issue by sagikazarmark** [woohoolabs/harmony#8]
It's an awesome (and free) CI service for code style. It closely follows php-cs-fixer fixers. As a general thumb rule, it's not a good practice to make a build fail because of CS.

See an example config here:

https://github.com/php-http/boilerplate/blob/master/.styleci.yml

**Comment by kocsismate** [comment]
Done! Thank you for the recommendation, it is a nice service indeed!
