### ISSUE TITLE
A few travis config observations

### ISSUE THREAD

**Issue by sagikazarmark** [woohoolabs/harmony#9]
1. As @xabbuh pointed somewhere, caching `$HOME/.composer/cache/files` is better. I think the reasoning was related to repository file caching which might delay updated package installation.
2. Since the composer packages are cached (and installed from dist, not git repo) caching vendor is pointless IMO.
3. What's the reason for installing "nikic/fast-route zendframework/zend-diactoros" in travis and not as dev deps in composer?
4. To remove some branching and make things more linear, see [this](https://github.com/php-http/boilerplate/blob/master/.travis.yml#L37) solution for running tests with or without coverage

**Comment by kocsismate** [comment]
Thanks for these recommendations, I'll definitely have a deeper look at them during the weekend. By the way, the entire Travis config was copied from Zend Diactoros :D So now, it's time to rethink things!

**Comment by kocsismate** [comment]
1. Done
2. Done
3. It was a really big oversight from me, thanks for pointing this out.. I thought that dev dependencies are also installed recursively that's why I didn't want to pollute the end users' vendor directory with Harmony's dev dependencies.
4. That's a really nice solution indeed, I updated my config.

Please review this commit if you have time: https://github.com/woohoolabs/harmony/commit/6994508ad8f8d9ddcb46631c129edd32e0f129a8

**Comment by sagikazarmark** [comment]
Added a few comments

**Comment by sagikazarmark** [comment]
I would suggest adding an environment to the matrix which tests dependencies against the lowest versions as well: https://github.com/php-http/httplug/blob/master/.travis.yml#L28

The rationale behind is to make sure that the given lowest version constraints are actually supported (composer always installs the latest possible versions)

**Comment by kocsismate** [comment]
When I was reading this suggestion, I realized that as I only run unit tests (and not integration tests), I shouldn't require Diactoros and FastRoute as dev dependencies at all, I should mock them instead in the tests. So I'll probably be able to remove them from the composer.json.

**Comment by sagikazarmark** [comment]
Well, there are two things to consider: One is that during development you might actually want to do functional testing which requires an implementation. The other is that (as you said) in unit tests you should mock the external dependencies. (However, in our case the external dependencies are (kind of) Value Objects in which case it is not always so obvious).

Another reason why you might want to install actual implementations as dev dependencies: you can add virtual packages as requirements (eg. psr/http-message-implementation) which requires a package that provides that virtual package, even in dev.

**Comment by kocsismate** [comment]
Requiring a psr/http-message-implementation dependency really makes sense! I've added it in this commit (https://github.com/woohoolabs/harmony/commit/f460540b09ef689bfb1cd2c582c327ce87884cd9).

Furthermore, it came to my mind that Harmony provides a really dump [container-interop implementation](https://github.com/woohoolabs/harmony/blob/master/src/Container/BasicContainer.php) so I reflected this in the following commit: https://github.com/woohoolabs/harmony/commit/6d95d23b7cce92bafaf5f2dcff190be731ae36a3

**Comment by sagikazarmark** [comment]
> Requiring a psr/http-message-implementation dependency really makes sense!

:+1: 

> Harmony provides a really dump

What does it mean? Dummy? Dumb?

If it is not actually meant to be used then maybe providing the package is not so good idea. Just my 2 cents.

**Comment by kocsismate** [comment]
I mean dumb :D

But it is fully functional and it can be used if your controllers don't have any dependencies and you don't want a more sophisticated container-interop compliant DIC.

**Comment by sagikazarmark** [comment]
I see. Well, if it actually makes sense to reuse it, then of course it makes sense to provide that package.

**Comment by kocsismate** [comment]
I am closing the issue now, but feel free to reopen it if you think something is missing.
